version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: vuekanban
    volumes: 
      - ./:/var/www/html
    ports:
      - 8089:80
    network_mode: "host"
